// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJMtnRL8SZyoQGpZBYn49W4kTSAcA_BM',
    appId: '1:291236876533:web:7411572f482b1ad3a6f5bc',
    messagingSenderId: '291236876533',
    projectId: 'mydiet-6ee55',
    authDomain: 'mydiet-6ee55.firebaseapp.com',
    storageBucket: 'mydiet-6ee55.appspot.com',
    measurementId: 'G-B0G868PWLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21nTMx1sXcEyGJ5b-KskMH2pbdBXooSk',
    appId: '1:291236876533:android:d84be369ff9faf78a6f5bc',
    messagingSenderId: '291236876533',
    projectId: 'mydiet-6ee55',
    storageBucket: 'mydiet-6ee55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZi2Z4LsX68--24foe7QeOqsaPzoqGVY',
    appId: '1:291236876533:ios:dfe62c890dd59373a6f5bc',
    messagingSenderId: '291236876533',
    projectId: 'mydiet-6ee55',
    storageBucket: 'mydiet-6ee55.appspot.com',
    iosClientId: '291236876533-htkheea27s7ludj24ocjfak50efpof80.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZi2Z4LsX68--24foe7QeOqsaPzoqGVY',
    appId: '1:291236876533:ios:dfe62c890dd59373a6f5bc',
    messagingSenderId: '291236876533',
    projectId: 'mydiet-6ee55',
    storageBucket: 'mydiet-6ee55.appspot.com',
    iosClientId: '291236876533-htkheea27s7ludj24ocjfak50efpof80.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
